name: clean_arch_lint
description: Custom lint rules for enforcing Clean Architecture boundaries in Flutter/Dart projects.
version: 1.1.0

repository: https://github.com/saulogatti/clean_arch_lint

environment:
  sdk: ">=3.10.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analysis_server_plugin: ^0.3.3
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
