name: clean_archt_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
repository: https://github.com/saulogatti/clean_archt_lint

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.8.1
  # path: ^1.9.0
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
