name: clean_arch_lint
description: Custom lint rules for enforcing Clean Architecture boundaries in Flutter/Dart projects.
version: 1.1.0

repository: https://github.com/saulogatti/clean_arch_lint

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^8.4.0
  custom_lint_builder: ^0.8.1
  path: ^1.9.0

dev_dependencies:
  custom_lint: ^0.8.1
  lints: ^6.0.0
  test: ^1.25.6
