name: clean_archt_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
repository: https://github.com/saulogatti/clean_archt_lint

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  custom_lint_builder: ^0.8.1
  path: ^1.9.0

dev_dependencies:
  custom_lint: ^0.8.1
  lints: ^6.0.0
  test: ^1.25.6
